kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    pull: if-not-exists
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST:
        from_secret: ssh_host
      SSH_PORT:
        from_secret: ssh_port
    commands:
      - echo "192.168.1.63 git.wangyuhui.top" >> /etc/hosts
      - mkdir $HOME/.ssh && echo -e "$SSH_KEY" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
      - |
        [[ -n "$${SSH_PORT}" ]] && [[ -n "$${SSH_HOST}" ]] && ssh-keyscan -p $${SSH_PORT} $${SSH_HOST} >> $HOME/.ssh/known_hosts
      - |
        [[ -z "$${SSH_PORT}" ]] && [[ -n "$${SSH_HOST}" ]] && ssh-keyscan $${SSH_HOST} >> $HOME/.ssh/known_hosts
      - git init && git remote add origin ${DRONE_GIT_SSH_URL} && git pull origin ${DRONE_COMMIT_BRANCH}
      - echo -n "latest,`date +%Y.%m.%d`" > .tags

  - name: build
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/wangyuhui/sanic-tailor
      username:
        from_secret: aliyun-username
      password:
        from_secret: aliyun-password
    when:
      branch:
      - master

  - name: deploy
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host: 192.168.1.63
      username:
        from_secret: ubuntu_username
      password:
        from_secret: ubuntu_password
      port: 22
      script:
        - cd /opt/sanic-tailor && docker-compose pull && docker-compose up -d

trigger:
  event:
    - push