version: '3.3'

services:
  sanic:
    image: sanic-tailor:latest
    volumes:
    - ./settings.py:/opt/sanic/settings.py
    ports:
    - 5000:5000
    - 5555:5555
    networks:
      - net

networks:
  net: