"""migration

Revision ID: 142cffd65d31
Revises: 7f66b99f9ceb
Create Date: 2021-11-04 13:58:59.171984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142cffd65d31'
down_revision = '7f66b99f9ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
