"""1 migration

Revision ID: 48fd8f4a5231
Revises: 
Create Date: 2021-11-04 11:29:51.523267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fd8f4a5231'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('write_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('create_uid', sa.INTEGER(), nullable=True),
    sa.Column('write_uid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['write_uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
