"""       0 migration

Revision ID: 5a26021efd79
Revises: 
Create Date: 2021-11-07 17:09:51.013502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a26021efd79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('write_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('create_uid', sa.BigInteger(), nullable=True),
    sa.Column('write_uid', sa.BigInteger(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_crypt', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['write_uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('message_contents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('write_date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('create_uid', sa.BigInteger(), nullable=True),
    sa.Column('write_uid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['write_uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_rooms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('write_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('create_uid', sa.BigInteger(), nullable=True),
    sa.Column('write_uid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['write_uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_room_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['message_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'room_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('write_date', sa.DateTime(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=True),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('create_uid', sa.BigInteger(), nullable=True),
    sa.Column('write_uid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['message_contents.id'], ),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['message_rooms.id'], ),
    sa.ForeignKeyConstraint(['write_uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('message_room_users')
    op.drop_table('message_rooms')
    op.drop_table('message_contents')
    op.drop_table('users')
    # ### end Alembic commands ###
