"""1 migration

Revision ID: 7f66b99f9ceb
Revises: c9c75a84ffa6
Create Date: 2021-11-04 11:55:04.137647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f66b99f9ceb'
down_revision = 'c9c75a84ffa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_uid', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('write_uid', sa.BigInteger(), nullable=True))
    op.drop_constraint('users_Updater_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_Creator_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['create_uid'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['write_uid'], ['id'])
    op.drop_column('users', 'Creator')
    op.drop_column('users', 'Updater')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Updater', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('Creator', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_Creator_fkey', 'users', 'users', ['Creator'], ['id'])
    op.create_foreign_key('users_Updater_fkey', 'users', 'users', ['Updater'], ['id'])
    op.drop_column('users', 'write_uid')
    op.drop_column('users', 'create_uid')
    # ### end Alembic commands ###
