"""1 migration

Revision ID: c9c75a84ffa6
Revises: 48fd8f4a5231
Create Date: 2021-11-04 11:49:49.311874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c75a84ffa6'
down_revision = '48fd8f4a5231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Creator', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('Updater', sa.INTEGER(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('users_create_uid_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_write_uid_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['Updater'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['Creator'], ['id'])
    op.drop_column('users', 'create_uid')
    op.drop_column('users', 'write_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('write_uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('create_uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_write_uid_fkey', 'users', 'users', ['write_uid'], ['id'])
    op.create_foreign_key('users_create_uid_fkey', 'users', 'users', ['create_uid'], ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'Updater')
    op.drop_column('users', 'Creator')
    # ### end Alembic commands ###
